# Generated by Django 4.1.5 on 2023-06-19 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='uploaded_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 19, 11, 37, 47, 806086)),
        ),
    ]
