# Generated by Django 4.1.5 on 2023-07-10 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_likes_post_post_likes_likes_comments'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='likes',
            table='likes',
        ),
    ]
